### ISSUE TITLE
Lack of Windows tutorial

### ISSUE THREAD

**Issue by AurusHuang** [leonardvandriel/caffe2_cpp_tutorial#1]
I believe this tutorial is not completely OS-agnostic, as it supposes that the tutorial should run on Unix-like OSes very subtly. Windows has no convenient programming tools like `make` by default, so a separate CMake or VS tutorial for Windows is required.

**Comment by leonardvandriel** [comment]
Hi @AurusHuang, thanks for reporting this. I was indeed a bit optimistic calling it OS-agnostic. I'll update the docs to be a bit more subtle. Regarding that separate tutorial: Windows, in particular VS, are out of my scope. I'm happy to include a patch if you are interested in providing that.

**Comment by AurusHuang** [comment]
Thank you for your response. However, I'm a newbie to Caffe2 and I cannot even run a tutorial myself. I can only hope you, if not anyone else, to be kind enough to release a Windows tutorial.

**Comment by AurusHuang** [comment]
@leonardvandriel I'm now making some progress on running the tutorial. However, I'm not skilled enough to make a CMake script for it. 
In Visual Studio, I manually added these values to make the intro program running: 
1. Include directories of: Caffe2, Caffe2/build, Protobuf, Eigen. 
2. Library directories and .lib filenames of: Caffe2, Protobuf/Protoc, OpenCV. LMDB. LevelDB. 
3. Additional linker parameters (for LINK.EXE): /WHOLEARCHIVE:Caffe2_CPU.lib  
Perhaps you can add some entries in CMake for include and library directories (while in POSIX systems, these directories and libraries are automatically found).

**Comment by leonardvandriel** [comment]
Good to hear you we're able to get the intro to work. I'm happy add some things to the `CMakeLists.txt`, but since i'm not able to test any of that, i'd still prefer to just merge a pull request that you were able to run and verify on a Windows machine.

A word of encouragement: CMake isn't that hard; the docs are pretty good and there's plenty of stackoverflow answers.

Did you also manage to run MNIST and the the other examples? These pose some additional challenges with respect to linking to OpenCV and CUDA libraries.

**Comment by AurusHuang** [comment]
Thank you. This will be enough for now.
发自我的 iPhone

在 2017年7月21日，03:08，Leo Vandriel <notifications@github.com<mailto:notifications@github.com>> 写道：


Good to hear you we're able to get the intro to work. I'm happy add some things to the CMakeLists.txt, but since i'm not able to test any of that, i'd still prefer to just merge a pull request that you were able to run and verify on a Windows machine.

A word of encouragement: CMake isn't that hard; the docs are pretty good and there's plenty of stackoverflow answers.

Did you also manage to run MNIST and the the other examples? These pose some additional challenges with respect to linking to OpenCV and CUDA libraries.
