### ISSUE TITLE
CMake Error: The following variables are used in this project

### ISSUE THREAD

**Issue by innnk** [leonardvandriel/caffe2_cpp_tutorial#10]
Hi
**I have an issue during making the folder.**
``` 
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
NCCL_LIB
    linked by target "intro" in directory /home/innnk/caffe2_cpp_tutorial
    linked by target "imagenet" in directory /home/innnk/caffe2_cpp_tutorial
    linked by target "train" in directory /home/innnk/caffe2_cpp_tutorial
    linked by target "dream" in directory /home/innnk/caffe2_cpp_tutorial
    linked by target "mnist" in directory /home/innnk/caffe2_cpp_tutorial
    linked by target "toy" in directory /home/innnk/caffe2_cpp_tutorial
    linked by target "pretrained" in directory /home/innnk/caffe2_cpp_tutorial
    linked by target "diff" in directory /home/innnk/caffe2_cpp_tutorial
    linked by target "inspect" in directory /home/innnk/caffe2_cpp_tutorial
    linked by target "retrain" in directory /home/innnk/caffe2_cpp_tutorial
    linked by target "rnn" in directory /home/innnk/caffe2_cpp_tutorial

-- Configuring incomplete, errors occurred!
See also "/home/innnk/caffe2_cpp_tutorial/build/CMakeFiles/CMakeOutput.log".
See also "/home/innnk/caffe2_cpp_tutorial/build/CMakeFiles/CMakeError.log".
make[1]: Entering directory '/home/innnk/caffe2_cpp_tutorial/build'
make[1]: *** 没有指明目标并且找不到 makefile。 停止。
make[1]: Leaving directory '/home/innnk/caffe2_cpp_tutorial/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2
```
**There are some error messages in CMakeError.log**
1. `在函数‘main’中：
CheckSymbolExists.c:(.text+0x16)：对‘pthread_create’未定义的引用(in function ‘main’:
CheckSymbolExists.c:(.text+0x16)：Undefined reference to 'pthread_create')`
2. `CMakeFiles/cmTC_735cf.dir/build.make:97: recipe for target 'cmTC_735cf' failed`
3. `Makefile:126: recipe for target 'cmTC_735cf/fast' failed`
4. `/usr/bin/ld: can't find -lpthreads`
I've already installed caffe2 with cuda 8.0 and it is working well.
Any suggestion will be appreciated. Thanks a lot~~

**Comment by ccchan0109** [comment]
I got the same issue...

**Comment by ccchan0109** [comment]
But I still got the same error > <

**Comment by innnk** [comment]
@ccchan0109 thx.

I tried to add nccl to the CMAKE_LIBRARY_PATH:

`export CMAKE_LIBRARY_PATH=$CMAKE_LIBRARY_PATH:$HOME/caffe2/third_party/nccl/build/lib`
in `$HOME/.bashrc`but it doesn't work.  \ \(╯-╰)/

**Comment by youngxiao** [comment]
@leonardvandriel I got the same problem when I make the `caffe2_cpp_tutorials`. 

> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> NCCL_LIB
>     linked by target "intro" in directory /home/innnk/caffe2_cpp_tutorial
>     linked by target "imagenet" in directory /home/innnk/caffe2_cpp_tutorial
>     linked by target "train" in directory /home/innnk/caffe2_cpp_tutorial
>     linked by target "dream" in directory /home/innnk/caffe2_cpp_tutorial
>     linked by target "mnist" in directory /home/innnk/caffe2_cpp_tutorial
>     linked by target "toy" in directory /home/innnk/caffe2_cpp_tutorial
>     linked by target "pretrained" in directory /home/innnk/caffe2_cpp_tutorial
>     linked by target "diff" in directory /home/innnk/caffe2_cpp_tutorial
>     linked by target "inspect" in directory /home/innnk/caffe2_cpp_tutorial
>     linked by target "retrain" in directory /home/innnk/caffe2_cpp_tutorial
>     linked by target "rnn" in directory /home/innnk/caffe2_cpp_tutorial

And I am sure I have installed the dependencies. Also I add the `$CMAKE_LIBRARY_PATH`.

> young@yang-xiao:~/DeepLearning/caffe2_cpp_tutorial$ echo $CMAKE_LIBRARY_PATH
> /home/young/pytorch/caffe2/third_party/nccl/build/lib

But still a make Error.
