### ISSUE TITLE
How to add gradient ops for multi loss ?

### ISSUE THREAD

**Issue by tpys** [leonardvandriel/caffe2_cpp_tutorial#11]
@leonardvandriel Tanks for this great tutorial, i learn a lot from it. However i met a problem and don't know how to solve it. I want to add multi loss operators into mnist.cc example, SoftmaxWithLoss and CenterLoss(new operator by myself, simply translate caffe-face's centerloss), i add gradient operators with following code:   

`predict.AddCenterLossOp("fc3", "label", "loss_reg", 10, 0, 0.2);
  predict.AddLabelCrossEntropyOp("softmax", "label", "xent");
  predict.AddAveragedLossOp("xent", "loss");
  AddAccuracy(init, predict);
  predict.AddConstantFillWithOp(1.f, "loss", "loss_grad");
  predict.AddConstantFillWithOp(1.f, "loss_reg", "loss_reg_grad");
  predict.AddGradientOps();`

then i print these two kinds of loss, it doesn't seem right, i think the backward gradients are wrong, wich should  come from two parts, centerloss and softmax loss.

So, how can i add gradient ops for multi loss network, could you give me some examples? i really want to solve it, great thanks!!

**Comment by leonardvandriel** [comment]
Hi @tpys, thanks for reaching out. Using two loss operators is something I havent tried. Theoretically it should work as the gradient operators are added in reverse order. Have you tried to dump the model with gradient operators to see if they're all correctly added? Use `std::cout << predict.Proto();` or `std::cout << predict.Short();`. Also you might need to add some additional support for the center loss gradient to work, like adding it to `trainable_ops`. Could you provide the dump and the implementation of `AddCenterLossOp`?
