### ISSUE TITLE
Make Issue

### ISSUE THREAD

**Issue by Togame-san** [leonardvandriel/caffe2_cpp_tutorial#13]
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CURAND_LIB

Can you explain what is causing this error? Note that original there were two variables not found the NCCL was solved by the additional hint to export a new path to the .bashsrc.

**Comment by Togame-san** [comment]
Nevermind. I resolved it by installing CUDA dev kit. I believe I simply was missing the needed library.

**Comment by Togame-san** [comment]
I am reopening this mainly because I needed to run to be able to make the project:
sudo apt install nvidia-cuda-toolkit

I am wondering if you can confirm this was a necessary step?

**Comment by leonardvandriel** [comment]
I agree with reopening this. It shouldn't be necessary to install NVIDIA software to run any of the examples. I currently don't have a system that doesn't have it installed, so I cannot easily verify a fix, but will take a look. Thanks.

**Comment by leonardvandriel** [comment]
Which commit are you currently on? The current CMake configuration does not contain any direct references to `CURAND_LIB`.

**Comment by Togame-san** [comment]
It was a past commit. I believe you already addressed this in a prior issue. I am closing this because it is outdated and should exist solely in case any poor sap clone a past commit.
