### ISSUE TITLE
What version of caffe2 are you using?

### ISSUE THREAD

**Issue by jwatte** [leonardvandriel/caffe2_cpp_tutorial#14]
Your transcription of MNIST to C++ includes caffe/util/net.h and uses NetUtil class.
Neither of them are available in current caffe2 trunk on github?

**Comment by leonardvandriel** [comment]
It's part of this repo, see [net.h](https://github.com/leonardvandriel/caffe2_cpp_tutorial/blob/master/include/caffe2/util/net.h) and [net.cc](https://github.com/leonardvandriel/caffe2_cpp_tutorial/blob/master/src/caffe2/util/net.cc). I put it in the same namespace and similar include path, which is maybe a bit confusing. It's like an extension to the Caffe2 repo.

**Comment by jwatte** [comment]
Ah! That makes your tutorial a tutorial in how to use your support library, rather than in how to use caffe2 ... Digging through the support library is actually much more illuminating than the "tutorial" MNIST file.

**Comment by leonardvandriel** [comment]
good point, I'll add that to the readme.
