### ISSUE TITLE
Linking problem

### ISSUE THREAD

**Issue by BenwenZhang** [leonardvandriel/caffe2_cpp_tutorial#16]
What's the reason of this linking problem? Thanks.
 make all
[ 40%] Built target caffe2_cpp
[ 43%] Linking CXX executable ../bin/train
Undefined symbols for architecture x86_64:
  "caffe2::OpSchema::Arg(char const*, char const*, bool)", referenced from:
      ___cxx_global_var_init.3 in libcaffe2_cpp.a(affine_scale_op.cc.o)
      ___cxx_global_var_init.3 in libcaffe2_cpp.a(back_mean_op.cc.o)
      ___cxx_global_var_init.3 in libcaffe2_cpp.a(diagonal_op.cc.o)
      ___cxx_global_var_init.1 in libcaffe2_cpp.a(time_plot_op.cc.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [../bin/train] Error 1
make[2]: *** [CMakeFiles/train.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2

**Comment by smil4ever** [comment]
@BenwenZhang
Which OS do you compile on? You can not copy the libs compiled on Ubuntu X86_64 to other OS like MacOS X86_86. The architectures is different. Recompile Caffe2 and caffe2_cpp_tutorial on the same OS env.
