### ISSUE TITLE
about usage of ModelUtil

### ISSUE THREAD

**Issue by breadbread1984** [leonardvandriel/caffe2_cpp_tutorial#17]
I read mnist.cc in your tutorial. I found that the operators are added in different way in AddTrainingOperators. I know that the operator which has initializable parameters is actually two operators in initNet and predictNet respectively. But for the operators which has no intializable parameters, can I add them through just model.Add....() functions rather than model.predict.Add...() functions?

**Comment by leonardvandriel** [comment]
Hi,

Indeed `model.Add...()` does more high-level modifications on both the init and predict model, while `model.predict.Add...()` just adds a single operator to either the init or predict `NetDef`. They do not overlap, as in, you either use one or the other.

The idea behind this is that `NetUtil` is simply a wrapper around Caffe2's `NetDef`. It allows you to more easily add operators and gradients and some debugging stuff like printing. On the other hand `ModelUtil` is more of a replacement of `ModelHelper` in Python Caffe2, of which there's no equivalent in C++ Caffe2.

**Comment by breadbread1984** [comment]
OK, thx!
