### ISSUE TITLE
about AddInput

### ISSUE THREAD

**Issue by breadbread1984** [leonardvandriel/caffe2_cpp_tutorial#18]
I am wondering about the what model.predict.AddInput() does in mnist.cc in your tutorial. I see that blobs are created automatically when the related operators are created with the help of model helper. So I am not sure what model.predict.AddInput() does with all the blobs already created. I can't find its counterpart in the python tutorial. Therefore, I can only rely on your help. Thx.

**Comment by leonardvandriel** [comment]
`model.predict.AddInput()` simply adds an external input to the predict `NetDef`. You're right that the model helper also adds external inputs, but in some cases we need to add a couple more manually.

For example:

    model.init.AddCreateDbOp("dbreader", db_type, db);
    model.predict.AddInput("dbreader");

Here we add a database reader directly to the init net, so we need to manually add this as an input to the predict net. We could of course write a helper method in `model` that does these two thing for us.

Did you get a chance to look at the source of `NetUtil` and `ModelUtil`? They're pretty straight forward.

**Comment by breadbread1984** [comment]
got it
