### ISSUE TITLE
 nullptr in dream

### ISSUE THREAD

**Issue by amandeepsaini** [leonardvandriel/caffe2_cpp_tutorial#20]
I can get dream to run on the first layer of GoogleNet, but layers beyond that (for example, as in the command you have in the readme) result in the error below:

> loading model..
> split model..
> running model..
> start size: 73
> terminate called after throwing an instance of 'caffe2::EnforceNotMet'
>   what():  [enforce fail at blob.h:76] IsType<T>(). wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor<caffe2::CUDAContext> .
> Offending Blob name: _norm2_scale.
> Error from operator: 
> input: "conv2" input: "norm2" input: "_norm2_scale" input: "norm2_grad" output: "conv2_grad" name: "" type: "LRNGradient" arg { name: "size" i: 5 } arg { name: "alpha" f: 0.0001 } arg { name: "beta" f: 0.75 } arg { name: "bias" f: 1 } arg { name: "order" s: "NCHW" } device_option { device_type: 1 } engine: "CUDNN" is_gradient_op: true
> *** Aborted at 1507278978 (unix time) try "date -d @1507278978" if you are using GNU date ***
> PC: @     0x7f26d0972428 gsignal
> *** SIGABRT (@0x3e800001da2) received by PID 7586 (TID 0x7f26d98d8e80) from PID 7586; stack trace: ***
>     @     0x7f26d6439390 (unknown)
>     @     0x7f26d0972428 gsignal
>     @     0x7f26d097402a abort
>     @     0x7f26d12b584d __gnu_cxx::__verbose_terminate_handler()
>     @     0x7f26d12b36b6 (unknown)
>     @     0x7f26d12b3701 std::terminate()
>     @     0x7f26d12b3969 __cxa_rethrow
>     @           0x5bd9ab caffe2::Operator<>::Run()
>     @     0x7f26d8eec888 caffe2::SimpleNet::Run()
>     @           0x52d677 caffe2::run()
>     @           0x52e3de main
>     @     0x7f26d095d830 __libc_start_main
>     @           0x526739 _start
>     @                0x0 (unknown)
> Aborted (core dumped)

Similar thing happens if I run it with AlexNet -- first layer runs fine, but latter layers run into norm1_scale or norm2_scale being uninitialized. Any ideas on how to resolve this?

**Comment by leonardvandriel** [comment]
Hi @amandeepsaini,

Which build (tag or commit) of Caffe2 are you using? I believe this is an issue in Caffe2's cuDNN implementation and was resolved recently.

To remedy the issue right now, you could run dream with `--device cuda`, which forces to not use cuDNN. Let me know if that works.

**Comment by amandeepsaini** [comment]
Yes, that worked, thank you!

Git log informs me that I built on this commit:

> 
> commit a06ebc17d361f68134ad63e6cc300da1123cad25
> Author: Hao Lu <hlu@fb.com>
> Date:   Tue Aug 22 18:08:34 2017 -0700
>
