### ISSUE TITLE
Saved model from "mnist" example cannot be read by "pretrained" example

### ISSUE THREAD

**Issue by ShunChengWu** [leonardvandriel/caffe2_cpp_tutorial#22]
Hi @leonardvandriel , 
I manage to load saved model built from MNIST example. However, it doesn't work because of lack of output. I inserted `op->add_output(param);` to line 317 solved this but another issue showed:
`op Conv: Source for input data is unknown for net mnist_model_predict, operator input: "data" input: "conv1_w" input: "conv1_b" output: "conv1" type: "Conv" arg { name: "stride" i: 1 } arg { name: "pad" i: 0 } arg { name: "kernel" i: 5 } 
`
I compared the pb file from model zoo and the one created by mnist example. It seems the data param is missing in the one created by mnist example.

**Comment by leonardvandriel** [comment]
Hi @ShunChengWu,

The `data` input is indeed missing. Thanks for pointing that out. I've update the MNIST example so it does add that external input.

This still means that you need to manually load the data when using the predict model. I deliberately kept that out of the pb file to avoid tying it to leveldb or any other input database. To show how this can be used, take a look at the `predict_example()` function in `mnist.cc`.

**Comment by ShunChengWu** [comment]
Thanks for your reply and example!
