### ISSUE TITLE
about rnn tutorial

### ISSUE THREAD

**Issue by breadbread1984** [leonardvandriel/caffe2_cpp_tutorial#25]
I can't figure out the role of prepare network. It seems the prepare network copies the last hidden status and cell status to the input of the LSTM after every sample is trained. But the next training sample is not what following the previous sequence in the text, so can't make use of the hidden and cell status. Is its purpose just to make the initial hidden and cell status random? Could I replace the prepare network with a random tensor filler?

**Comment by leonardvandriel** [comment]
Hi @breadbread1984,

This could be a bug in my code. I should take a closer look. 

Do you see the same thing happen in the original Caffe2 tutorial in [char_rnn.py](https://github.com/caffe2/caffe2/blob/master/caffe2/python/examples/char_rnn.py)?

**Comment by breadbread1984** [comment]
I am afraid that I am really not good at understanding Python code. That's why I am stick to your C++ model helper. :-P
