### ISSUE TITLE
Issue with training googlenet from scratch

### ISSUE THREAD

**Issue by zeratech** [leonardvandriel/caffe2_cpp_tutorial#26]
Hi , I got this error when I tried to train googlenet from scratch, any thoughts?

/caffe2_cpp_tutorial-master$ sudo ./bin/train --model googlenet --folder /home/ubuntu/data/SmallTrain

## CNN Training Example ##

optimizer: adam
device: cudnn
using cuda: true
dump-model: false
model: googlenet
layer:
image-dir: /home/ubuntu/data/SmallTrain
db-type: leveldb
size: 224
epochs: 1000
test-runs: 50
batch: 64
lr: 0.0001
skip_preprocess: false
zero-one: false
display: false
reshape: false

2 labels found:
  0: Dogs #65
  1: Cats #50
115 files found
115 images cached

training..
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at blob.h:76] IsType<T>(). wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor<caffe2::CUDAContext> .
Offending Blob name: _conv2/norm2_scale.
Error from operator:
input: "conv2/3x3" input: "conv2/norm2" input: "_conv2/norm2_scale" input: "conv2/norm2_grad" output: "conv2/3x3_grad" name: "" type: "LRNGradient" arg { name: "size" i: 5 } arg { name: "alpha" f: 0.0001 } arg { name: "beta" f: 0.75 } arg { name: "bias" f: 1 } arg { name: "order" s: "NCHW" } device_option { device_type: 1 } engine: "CUDNN" is_gradient_op: true
*** Aborted at 1509939039 (unix time) try "date -d @1509939039" if you are using GNU date ***
PC: @     0x7eff29eb5428 gsignal
*** SIGABRT (@0x6a2) received by PID 1698 (TID 0x7eff342e4e00) from PID 1698; stack trace: ***
    @     0x7eff31a12390 (unknown)
    @     0x7eff29eb5428 gsignal
    @     0x7eff29eb702a abort
    @     0x7eff2a7f884d __gnu_cxx::__verbose_terminate_handler()
    @     0x7eff2a7f66b6 (unknown)
    @     0x7eff2a7f6701 std::terminate()
    @     0x7eff2a7f6969 __cxa_rethrow
    @           0x5be8fd caffe2::Operator<>::Run()
    @     0x7eff33963a98 caffe2::SimpleNet::Run()
    @     0x7eff3398b060 caffe2::Workspace::RunNet()
    @           0x5294ae caffe2::run_trainer()
    @           0x52f1a4 caffe2::run()
    @           0x52ff57 main
    @     0x7eff29ea0830 __libc_start_main
    @           0x528d09 _start
    @                0x0 (unknown)
Aborted (core dumped)

**Comment by leonardvandriel** [comment]
Hi @zeratech, perhaps this is related to issue https://github.com/leonardvandriel/caffe2_cpp_tutorial/issues/20

Could you see if adding `--device cuda` works? Also, I haven't seen this error since Caffe2 v0.8.1

**Comment by zeratech** [comment]
Thanks that fixed the issue.
