### ISSUE TITLE
No explanation on how to use Fast Trained model

### ISSUE THREAD

**Issue by beardo01** [leonardvandriel/caffe2_cpp_tutorial#29]
I think it would be useful if you were to add an explanation on how to use the trained model once it has been trained. More of a suggestion than request.

Thanks!

**Comment by leonardvandriel** [comment]
Hi @beardo01, that's a good suggestion. I will add an entry to the readme to address this.

You can use the model like any other trained CNN model in Caffe2. For example by loading it into the `imagenet` example. Say you trained with:

    ./bin/train --model googlenet --folder res/images --layer pool5/7x7_s1

This will store the output model in `res/images/_pool5_7x7_s1_googlenet_%_net.pb`. You can now use the imagenet classifier using:

    ./bin/imagenet --model res/images/_pool5_7x7_s1_googlenet_%_net.pb --file res/images/dog/Tjoise.jpg

Note that the labels are incorrect here, as they are taken from the ImageNet dataset, so only look at the index of the label.

Thanks for pointing this out.

**Comment by beardo01** [comment]
Cheers, thanks for the update! Much appreciated.
