### ISSUE TITLE
CMake error Eigen3

### ISSUE THREAD

**Issue by Sparkier** [leonardvandriel/caffe2_cpp_tutorial#3]
By following your instructions, I get the following error:

```
CMake Error at CMakeLists.txt:6 (find_package):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.
```

Im running Ubuntu 16.04 LTS.

**Comment by leonardvandriel** [comment]
Hi @Sparkier. The readme is indeed not mentioning the _Eigen_ package, which is required for the tutorials. You can install it with:

    sudo apt-get install libeigen3-dev

I updated the readme. Let me know if that works. Thanks for reporting.

**Comment by Sparkier** [comment]
Hello @leonardvandriel ,  that indeed solved the issue with not finding the package. However, when running `make` inside `caffe3_cpp_tutorial`, which I assume should build all the tutorials, i get another error. 

`CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
NCCL_LIB
    linked by target "train" in directory /home/***********/caffe2_cpp_tutorial
    linked by target "retrain" in directory /home/***********/caffe2_cpp_tutorial
    linked by target "imagenet" in directory /home/***********/caffe2_cpp_tutorial
    linked by target "dream" in directory /home/***********/caffe2_cpp_tutorial
    linked by target "mnist" in directory /home/***********/caffe2_cpp_tutorial
`

**Comment by leonardvandriel** [comment]
can you see what happens if you add nccl to the `CMAKE_LIBRARY_PATH`:

    export CMAKE_LIBRARY_PATH=$CMAKE_LIBRARY_PATH:$HOME/caffe2/third_party/nccl/build/lib

Make sure you change `$HOME/caffe2` into where you installed caffe2. If that works, consider adding the line to your `.bashrc`.

**Comment by Sparkier** [comment]
Thank you, that did the trick. Don't know if that belongs here anymore though since it's not related to Eigen3.

**Comment by leonardvandriel** [comment]
no worries, excellent question. I'll add it to the readme.
