### ISSUE TITLE
make issue

### ISSUE THREAD

**Issue by mahsaayi** [leonardvandriel/caffe2_cpp_tutorial#30]
hello, I have the following issue through making:

Scanning dependencies of target train
[ 55%] Building CXX object CMakeFiles/train.dir/src/caffe2/binaries/train.cc.o
[ 57%] Linking CXX executable bin/train
/usr/bin/ld: warning: libicui18n.so.56, needed by //home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicuuc.so.56, needed by //home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicudata.so.56, needed by //home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5, not found (try using -rpath or -rpath-link)
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `u_strToLower_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucnv_getStandardName_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucnv_getAlias_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `uenum_next_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `u_strToUpper_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucnv_setSubstChars_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucal_getTimeZoneDisplayName_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucnv_fromUnicode_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `u_errorName_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `uenum_close_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucal_getDSTSavings_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucal_openTimeZoneIDEnumeration_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucal_setMillis_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucol_close_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucol_getSortKey_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucal_get_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucol_open_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucnv_compareNames_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucal_clone_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucal_open_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucol_setAttribute_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucal_openCountryTimeZones_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucnv_open_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucal_openTimeZones_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucnv_countAliases_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucal_inDaylightTime_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucal_close_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucnv_getAvailableName_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucnv_getDefaultName_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucal_getDefaultTimeZone_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucnv_toUnicode_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucol_strcoll_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucnv_close_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucnv_getMaxCharSize_56'
//home/installzoo/Programs/Qt5.7.0/5.7/gcc_64/lib/libQt5Core.so.5: undefined reference to `ucnv_countAvailable_56'
collect2: error: ld returned 1 exit status
CMakeFiles/train.dir/build.make:134: recipe for target 'bin/train' failed
make[2]: *** [bin/train] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/train.dir/all' failed
make[1]: *** [CMakeFiles/train.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mahsaayi** [comment]
please help me! @leonardvandriel

**Comment by leonardvandriel** [comment]
Hi @mahsaayi, there seems to be an issue with Qt5, which doesn't seem to be part of Caffe2 or this project. Did you make any modifications to the project that added dependency on Qt5? Perhaps try to (re)install Qt or any of the dependencies mentioned.

**Comment by mahsaayi** [comment]
Thank you for your answer. No I didn't make any modifications. but solved the problem with defining a LD_LIBRARY_PATH for qt.
