### ISSUE TITLE
Maybe a tutorial on how to use dumped proto to train models from c++?

### ISSUE THREAD

**Issue by rwangbd** [leonardvandriel/caffe2_cpp_tutorial#37]
First, thank you for the awesome work!

I wonder whether it would be possible to ask (beg) for a tutorial on how to train models from the dumped proto texts (from python)? According to the intro it is a main feature that dumped configuration can read into c++ but I haven't found any example. 

Thank you soooooo much in advance.

**Comment by leonardvandriel** [comment]
Hi, sorry for the delayed response.

If I understand correctly you have a model that you trained in python and now want to run this model on a device without python. If you have the two pb files `init` and `predict`, then take a look at the `predict_example()` method in `mnist.cc`. Is that useful?

I can put this in a separate tutorial specifically for you use case.

**Comment by rwangbd** [comment]
Hi,

Thank you for the response. In fact, it would nice if you can both show how to load pb for init as well as pb for predict. 

Thank you very much in advance!

**Comment by leonardvandriel** [comment]
Take a look at the [Pretrained tutorial](https://github.com/leonardvandriel/caffe2_cpp_tutorial#loading-pre-trained-models) and [pretrained.cc](https://github.com/leonardvandriel/caffe2_cpp_tutorial/blob/master/src/caffe2/binaries/pretrained.cc).
