### ISSUE TITLE
CMake Error: variables not found (GTEST_LIB)

### ISSUE THREAD

**Issue by hoebd** [leonardvandriel/caffe2_cpp_tutorial#39]
Hi, I get an error when executing cmake. How can I solve that issue?

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GTEST_LIB
    linked by target "net_test" in directory /home/daniel/cvhci/caffe2/caffe2_cpp_tutorial
    linked by target "net_gradient_test" in directory /home/daniel/cvhci/caffe2/caffe2_cpp_tutorial

**Comment by leonardvandriel** [comment]
thanks for reporting. fixed it in commit 5e30c6cbff
