### ISSUE TITLE
Error compiling cpp

### ISSUE THREAD

**Issue by jazzseow** [leonardvandriel/caffe2_cpp_tutorial#4]
I tried to compile the .cpp file and got errors like 
     "intro.cpp:(.text+0x1c23): undefined reference to `caffe2::NetDef::~NetDef()'" and a lot more similar to this

How do I compile your .cpp files without getting these errors?

**Comment by leonardvandriel** [comment]
Hi @jazzseow,

`caffe2::NetDef` is defined in `caffe2.pb.h` which is generated during the build proces in `<your-caffe2-folder>/build/caffe2/proto/caffe2.pb.h` and then installed somewhere in `/usr/local/include/caffe2/proto/caffe2.pb.h`.

Did you get any of Caffe2's own examples running?

Can you see if `caffe2.pb.h` is actually there in `/usr/local/include/caffe2/proto`?

It not, make sure to check the Caffe2 installation instructions, in particular running `sudo make install` from the Caffe2 `build` folder.

**Comment by jazzseow** [comment]
@leonardvandriel, 
1. I've used  `-std=c++11 -I/usr/local/include/eigen3/ intro.cpp` to compile the code. 
2. I've tried the python version of the tutorias and examples, and they are working fine. 
3. Yes, it's in the directory. 

Maybe I shouldn't compile it this way?

**Comment by alexge233** [comment]
Hi, sorry for jumping in.
The `undefined reference` is a **linking error** and not an inclusion issue.
You need to use `-L/usr/local/` or wherever you have installed the library `libCaffe2_GPU.so`

**Comment by leonardvandriel** [comment]
@jazzseow, the easiest way to build all sources, including intro.cpp is to run `make` from the project root. This will create a `build/` folder and run `cmake ..` from there. This will include building intro.cpp into the `bin/` folder.

As @alexge233 mentioned, if you want to manually build individual binaries, make sure to add `-I/usr/local/include`, and some other flags:

    c++ -std=gnu++11 -I/usr/local/include/eigen3 -I/usr/local/include/opencv -I/usr/local/include -Iinclude -L/usr/local/lib -lgflags -lglog -lprotobuf -lCaffe2_CPU  -o intro src/caffe2/binaries/intro.cpp

Building other examples will require more complicated build flags, which is why I recommend using CMake by running `make` in the project root.

**Comment by jazzseow** [comment]
@leonardvandriel Thanks, `c++ -std=gnu++11 -I/usr/local/include/eigen3 -I/usr/local/include/opencv -I/usr/local/include -Iinclude -L/usr/local/lib -lgflags -lglog -lprotobuf -lCaffe2_CPU -o intro src/caffe2/binaries/intro.cpp` works. 8 did build it successfully, I was just messing with the code, trying to figure out how it works. 

Thank you for this awesome tutorial
