### ISSUE TITLE
SpatialBN AddInput during training

### ISSUE THREAD

**Issue by ShunChengWu** [leonardvandriel/caffe2_cpp_tutorial#40]
https://github.com/leonardvandriel/caffe2_cpp_tutorial/blob/3ca1b6702f3ec73df7a5d0cf3fbb4cd58281baaa/src/caffe2/util/model.cc#L176

During training, it seems that
```
predict.AddInput(output + "_mean");
predict.AddInput(output + "_var");
```
still required. 

---
The other thing is:
https://github.com/leonardvandriel/caffe2_cpp_tutorial/blob/3ca1b6702f3ec73df7a5d0cf3fbb4cd58281baaa/src/caffe2/util/net_gradient.cc#L129
Why not add all meta.ops_? Instead of only using meta.ops_[0]. In the second case, some operations like BatchMatMul, MatMul, Mul will fail because of the lack of the gradient value of the second input.

**Comment by leonardvandriel** [comment]
Hi @ShunChengWu, 

Can you explain what you mean by "still required". The `"_mean"` input/output is only added if `test` is true, so the `ConstantFill` would also only be necessary then. Also, SpatialBN is static during testing, and therefore doesn't need the `_mean` and `_var` statistics.

About the second issue: that's indeed a bug and should add all meta ops. I didn't get around implementing this.

**Comment by ShunChengWu** [comment]
Hi @leonardvandriel, 
What I mean is during "training", the input should have 5 (input, mean, var, scale, bias). 
I haven't run this version of your code but in the old version, in this case, it will show something like 

> "op SpatialBN: Source for input output+ "_mean" is unknown"

Plus, during test time, base on the caffe2's original code
https://github.com/caffe2/caffe2/blob/master/caffe2/operators/spatial_batch_norm_gradient_op.cc#L137
five inputs are still required. I have tried using the `if else` part written here:
https://github.com/leonardvandriel/caffe2_cpp_tutorial/blob/3ca1b6702f3ec73df7a5d0cf3fbb4cd58281baaa/src/caffe2/util/model.cc#L177
During testing, it will show the message like this:
> Input size 3 not in range [min=5, max=5]. 

But one thing is that _mean and _var will need to be added to `pass_gradient` set

About the second problem, can you explain more about the bug? 
I am actually using all the meta ops and implement at the Pointnet network architecture and running without any errors. But the accuracy drops a bit from the original Pointnet network implemented in Tensorflow. I think the problem maybe is in the gradient part, especially in this meta ops. If you can provide me more information about this bug will be wonderful.

**Comment by leonardvandriel** [comment]
Thanks you for providing some more detail.

I've made some changes in the past month to allow for training Resnet50. Perhaps that could have fixed this issue. Here's an example from the resnet protocol buffer, for training:

```
op {
  input: "conv1_conv_relu"
  input: "conv1_spatbn_relu_s"
  input: "conv1_spatbn_relu_b"
  input: "conv1_spatbn_relu_rm"
  input: "conv1_spatbn_relu_riv"
  output: "conv1_spatbn_relu"
  output: "conv1_spatbn_relu_rm"
  output: "conv1_spatbn_relu_riv"
  output: "conv1_spatbn_relu_rm_save"
  output: "conv1_spatbn_relu_riv_save"
  type: "SpatialBN"
  arg {
    name: "is_test"
    i: 0
  }
  ...
}
```

and for testing:

```
op {
  input: "conv1_conv_relu"
  input: "conv1_spatbn_relu_s"
  input: "conv1_spatbn_relu_b"
  input: "conv1_spatbn_relu_rm"
  input: "conv1_spatbn_relu_riv"
  output: "conv1_spatbn_relu"
  type: "SpatialBN"
  arg {
    name: "is_test"
    i: 1
  }
  ...
}
```

As you can see both have 5 inputs, but a different number of outputs. Here I followed the the [operator documentation](https://caffe2.ai/docs/operators-catalogue.html#spatialbn) and the [resnet50_trainer](https://github.com/caffe2/caffe2/blob/master/caffe2/python/examples/resnet50_trainer.py). 

I couldn't find anything about a `pass_gradient` set.

**Comment by leonardvandriel** [comment]
Ok, i see now what you mean, sorry. Fixed in commit b26484f260.

**Comment by leonardvandriel** [comment]
On the `meta.ops_[0]` issue: I currently don't have any good test cases that use BatchMatMul, MatMul, or Mul, so I haven't been able to reproduce this. There's a fix in commit 888ad1d82a. Does that work for you?

**Comment by ShunChengWu** [comment]
Hey Thanks for the fix. 
About the `meta.ops_[0]` issue, I will try it later and see if it works.

**Comment by leonardvandriel** [comment]
Thank you too. If you have a specific example that requires multiple `meta.ops_`, then please share so I can focus on fixing that.
