### ISSUE TITLE
Cmake compile error

### ISSUE THREAD

**Issue by CuthbertJungle** [leonardvandriel/caffe2_cpp_tutorial#43]
i can't get the code to compile. i have the following error: 

david@david-W54-55SU1-SUW:~/Documents/Poker/caffe2_cpp_tutorial$ make
make[1]: Entering directory '/home/david/Documents/Poker/caffe2_cpp_tutorial/build'
CMake Error at CMakeLists.txt:5 (find_package):
  By not providing "Findcaffe2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "caffe2", but
  CMake did not find one.

  Could not find a package configuration file provided by "caffe2" with any
  of the following names:

    caffe2Config.cmake
    caffe2-config.cmake

  Add the installation prefix of "caffe2" to CMAKE_PREFIX_PATH or set
  "caffe2_DIR" to a directory containing one of the above files.  If "caffe2"
  provides a separate development package or SDK, be sure it has been
  installed.

I do have file "caffe2Config.cmake" which is at location "/home/david/caffe2/build". any ideas how i get this working. i'm new to cmake.

**Comment by leonardvandriel** [comment]
Hi @CuthbertJungle,

Thanks for reporting the issue. The CMake script expects Caffe2 to be installed on the system, which would place it under `/usr`. The solution would be to either install Caffe2 from the build folder with `sudo make install` (see Caffe2 [docs](https://caffe2.ai/docs/getting-started.html)), or to provide the path to Caffe2 with the `CMAKE_PREFIX_PATH` flag (see this [stackoverflow](https://stackoverflow.com/questions/7029371/how-to-point-cmake-at-specific-directory-for-library)).

**Comment by CuthbertJungle** [comment]
thanks ! i've got it working now. 

I added into caffe2_cpp_tutorial/CMakeLists.txt the following line:

export CMAKE_PREFIX_PATH=/usr/local/caffe2/
