### ISSUE TITLE
Can't find ModelDef or ModelMeta

### ISSUE THREAD

**Issue by ctraina** [leonardvandriel/caffe2_cpp_tutorial#48]
I've built caffe2 and successfully "borrowed" your tutorial and toy tests, but when I try to use your MNIST test, it can't find ModelDef or ModelMeta (build errors).  Where are these defined?

**Comment by leonardvandriel** [comment]
Hi, the MNIST example relies on `ModelDef` defined in [model.h](https://github.com/leonardvandriel/caffe2_cpp_tutorial/blob/master/include/caffe2/util/model.h). You will also need `NetDef` and the implementations in `src/caffe2/util`. You could just add the header files to your project and then link with the `libcaffe2_cpp.a` in the `build` folder. Alternatively you can include the sources, or just copy paste the methods MNIST uses, which are few.

**Comment by ctraina** [comment]
FYI:  I got this working, but one of the headaches was a hard-coded path to log data to /tmp (which crashed when it didn't exist).  In Windows, this folder only exists if you explicitly create it.
