### ISSUE TITLE
Example for loading data without using third party database?`

### ISSUE THREAD

**Issue by ctraina** [leonardvandriel/caffe2_cpp_tutorial#49]
I have been playing with your (awesome) run_mnist example.  I want to do something similar with a set of images/labels I already have.  However, I am having issues with generating a LevelDB database that will work if I use the exising LevelDB databases from https://download.caffe2.ai/datasets/mnist/mnist.zip, it works fine, but if I use the make_mnist_db.exe from the Caffe2 project, I get this exception in run_mnist:

Run MNIST Exception: [enforce fail at conv_op_impl.h:46] C == filter.dim32(1) * group_. Convolution op: input channels does not match: # of input channels 28 is not equal to kernel channels * group:1*1 Error from operator:
input: "data" input: "conv1_w" input: "conv1_b" output: "conv1" type: "Conv" arg { name: "stride" i: 1 } arg { name: "pad" i: 0 } arg { name: "kernel" i: 5 } arg { name: "order" s: "NCHW" }

Is there an example somewhere of how to load this data directly without having to use AddTensorProtosDbInputOp?

**Comment by leonardvandriel** [comment]
Hi. You can add feed data manually before every `RunOnce(..)`, see `pretrained.cc` for an example:

    auto input = workspace.CreateBlob("data")->GetMutable<TensorCPU>();
    input->ResizeLike(tensor);
    input->ShareData(tensor);
    CAFFE_ENFORCE(workspace.RunNetOnce(predict_net));

The error you get is related to input sizes, which is usually a bit of a tricky business as every dimension needs to be exactly right. You can insert an `AddCoutOp(..)` before the first convolution to log the input data. In the case of MNIST, it should be of dimensions (N, 28, 28, 1), where N is the batch size.

**Comment by ctraina** [comment]
FYI:  I got it working by comparing the bytes in the pre-built MNIST LevelDB database to the output from make_mnist_db, and for some reason, a couple of bits were swapped.  After a quick fix (hack), I have this working with my data.  Thanks!
