### ISSUE TITLE
CMakeLists.txt update for CURAND

### ISSUE THREAD

**Issue by alexge233** [leonardvandriel/caffe2_cpp_tutorial#5]
Hi,

The CUDA cmake module includes a variable ` ${CUDA_curand_LIBRARY}`,
so you don't need to manually search for `find_library(CURAND_LIB curand)`.

The `NCCL` appears to be **REQUIRED** if using CUDA? In which case, 
the `CMakeLists.txt` could maybe benefit from a `message(STATUS "NCCL lib in: ${NCCL}")` ?
Also, the `cmake ..` and `make` in the root directory is a wee bit confusing.

Another thing, I kept getting segfaults, because I hadn't run `./script/download_resource.sh` so maybe this should be in the `README.md` for silly people such as myself? :grinning:

By the way, thanks a ton for putting this repo together, it is really useful!!

Best,
Alex

diff-patch:

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 558a85b..b7c2bb0 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -23,7 +23,6 @@ find_library(CAFFE2_GPU_LIB Caffe2_GPU)
 find_library(GLOG_LIB glog)
 find_library(GFLAGS_LIB gflags)
 find_library(NCCL_LIB nccl)
-find_library(CURAND_LIB curand)
 
 if(NOT CAFFE2_LIB)
   message(FATAL_ERROR "Caffe2 lib not found")
@@ -75,7 +74,7 @@ if(OpenCV_LIBS)
 endif()
 
 if(CUDA_LIBRARIES)
-  list(APPEND ALL_LIBRARIES ${CUDA_LIBRARIES} ${CUDA_CUDART_LIBRARY} ${NCCL_LIB} ${CURAND_LIB})
+    list(APPEND ALL_LIBRARIES ${CUDA_LIBRARIES} ${CUDA_CUDART_LIBRARY} ${NCCL_LIB} ${CUDA_curand_LIBRARY})
   add_definitions(-DWITH_CUDA)
 endif()
```

**Comment by leonardvandriel** [comment]
Thanks Alex, really appreciate all that. I updated the CMake config with the two changes and added a mentioning of `./script/download_resource.sh` in the readme.

About he `cmake ..` and `make`: I copied this pattern from the Caffe2 CMake setup. The goal here is to keep all build products in the `build/` folder instead of the root. Is there a more elegant way to do this?

**Comment by alexge233** [comment]
I must have made a mistake, if you keep everything under `build` thats absolutely fine!
You could try to use `CMakeLists.txt` to download the models (I can provide the diff patch if you want), but I am assuming that users may already have the models downloaded from caffe?
Also, is NCCL a requirement or optional?

**Comment by leonardvandriel** [comment]
You're right. The NCCL reference is unnecessary; i removed it. For some reason it was needed in the past to resolve linker errors.

**Comment by alexge233** [comment]
You can still use it with a custom cmake flag, e.g., `-DUSE_NCCL` and then search for it.
Thanks for the examples, very useful 👍
