### ISSUE TITLE
Model serialization/deserialization error

### ISSUE THREAD

**Issue by ctraina** [leonardvandriel/caffe2_cpp_tutorial#59]
After training on the MNIST data, I am able to write the model to disk.  However, when I try to read it back in using ReadProtoFromFile, I get the following errors:

[libprotobuf ERROR c:\projects\caffe2\third_party\protobuf\src\google\protobuf\text_format.cc:288] Error parsing text-format caffe2.NetDef: 2:1: Invalid control characters encountered in text.
[libprotobuf ERROR c:\projects\caffe2\third_party\protobuf\src\google\protobuf\text_format.cc:288] Error parsing text-format caffe2.NetDef: 2:18: Invalid control characters encountered in text.
[libprotobuf ERROR c:\projects\caffe2\third_party\protobuf\src\google\protobuf\text_format.cc:288] Error parsing text-format caffe2.NetDef: 2:19: Interpreting non ascii codepoint 244.
[libprotobuf ERROR c:\projects\caffe2\third_party\protobuf\src\google\protobuf\text_format.cc:288] Error parsing text-format caffe2.NetDef: 2:19: Message type "caffe2.NetDef" has no field named "mnist_model_init".
Prediction Example Exception: [enforce fail at e:\projects\caffe2\run_mnist\run_mnist.cpp:660] ReadProtoFromFile(initModel.c_str(), &init_model).  I've attached the output files.  I'm running in Windows, if that wasn't obvious...

[mnist_model.zip](https://github.com/leonardvandriel/caffe2_cpp_tutorial/files/1835035/mnist_model.zip)

**Comment by leonardvandriel** [comment]
Hi, this might be related to loading the `.pbtxt` text format as binary. In general it's best to avoid using the text format. Does that help?

**Comment by ctraina** [comment]
Actually, I was calling ReadProtoFromFile on the two .pb files.  Is that not correct?  I was trying to follow your example code from the MNIST example:

// Write
deploy.predict.WriteText((FLAGS_output_folder + "mnist_predict_net.pbtxt").c_str());
// writes out mnist_init_net.pb, mnist_model_info.pb, and mnist_predict_net.pb
// NOTE: mnist_model_info.pb ends up with 0 bytes (?)
deploy.Write((FLAGS_output_folder + "mnist").c_str());

// Read
// initModel = path to mnist_init_net.pb written out by deploy.Write
CAFFE_ENFORCE(ReadProtoFromFile(initModel.c_str(), &init_model));
// predictModel = path to mnist_predict_net.pb written out by deploy.Write
CAFFE_ENFORCE(ReadProtoFromFile(predictModel.c_str(), &predict_model));

**Comment by ctraina** [comment]
Interestingly, it throws exceptions if I try to write the protos out as binary files and try to read them back, but it works if I write them out as text files and then read them back.  Go figure...

std::string initModel = FLAGS_output_folder + "mnist_predict_net.pb.txt";
std::string predictModel = FLAGS_output_folder + "mnist_init_net.pb.txt";

// Writing
deploy.predict.WriteText(initModel.c_str());
deploy.init.WriteText(predictModel.c_str());

// Reading
CAFFE_ENFORCE(ReadProtoFromFile(initModel.c_str(), &init_model));
CAFFE_ENFORCE(ReadProtoFromFile(predictModel.c_str(), &predict_model));
