### ISSUE TITLE
typeid.h:211: undefined reference to `caffe2::gTypeNames()'

### ISSUE THREAD

**Issue by wlgcqh** [leonardvandriel/caffe2_cpp_tutorial#79]
CC = g++
CFLAGS = -std=c++11 -g -O0 -Wall -Wfatal-errors  -I/home/beiqi.qh/workplace/opt/anaconda2/include
LDFLAGS = -L/home/beiqi.qh/workplace/opt/anaconda2/lib -lgflags -lglog -lprotobuf -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_imgcodecs  -lcaffe2_gpu -lcaffe2
EXEC = 'out'
all: main.o tool.o
  $(CC) $(CFLAGS)  $^  -o $(EXEC) $(LDFLAGS)
main.o: main.cpp tool.h
  $(CC) $(CFLAGS) -c main.cpp -o $@
tool.o: tool.cpp tool.h
  $(CC) $(CFLAGS) -c tool.cpp -o $@
clean:
  rm -f $(EXEC) main.o tool.o

when I typing make, 
/home/beiqi.qh/workplace/opt/anaconda2/include/caffe2/core/typeid.h:168: undefined reference to `caffe2::gTypeNames()'
/home/beiqi.qh/workplace/opt/anaconda2/include/caffe2/core/typeid.h:169: undefined reference to `caffe2::gTypeNames()'
main.o: In function `caffe2::Tensor<caffe2::CPUContext> const& caffe2::Blob::Get<caffe2::Tensor<caffe2::CPUContext> >() const':
/home/beiqi.qh/workplace/opt/anaconda2/include/caffe2/core/blob.h:79: undefined reference to `caffe2::EnforceNotMet::EnforceNotMet(char const*, int, char const*, std::string const&, void const*)'
main.o: In function `float const* caffe2::Tensor<caffe2::CPUContext>::data<float>() const':
/home/beiqi.qh/workplace/opt/anaconda2/include/caffe2/core/tensor.h:485: undefined reference to `caffe2::EnforceNotMet::EnforceNotMet(char const*,int, char const*, std::string const&, void const*)'
/home/beiqi.qh/workplace/opt/anaconda2/include/caffe2/core/tensor.h:490: undefined reference to `caffe2::EnforceNotMet::EnforceNotMet(char const*,int, char const*, std::string const&, void const*)'
main.o: In function `char const* caffe2::TypeMeta::TypeName<caffe2::Tensor<caffe2::CPUContext> >()':
/home/beiqi.qh/workplace/opt/anaconda2/include/caffe2/core/typeid.h:211: undefined reference to `caffe2::gTypeNames()'
/home/beiqi.qh/workplace/opt/anaconda2/include/caffe2/core/typeid.h:212: undefined reference to `caffe2::gTypeNames()'
main.o: In function `char const* caffe2::TypeMeta::TypeName<float>()':
/home/beiqi.qh/workplace/opt/anaconda2/include/caffe2/core/typeid.h:211: undefined reference to `caffe2::gTypeNames()'
/home/beiqi.qh/workplace/opt/anaconda2/include/caffe2/core/typeid.h:212: undefined reference to `caffe2::gTypeNames()'
collect2: error: ld returned 1 exit status
make: *** [all] Error 1

How to solve this problem?

**Comment by wlgcqh** [comment]
@leonardvandriel

**Comment by alexge233** [comment]
you aren't linking to `libcaffe2` properly which is why you are seeing undefined errors.
What is your `sudo ldconfig -p | grep "libcaffe2*"` output?

**Comment by wlgcqh** [comment]
thanks for your reply, I install caffe2 in "conda install -c caffe2 caffe2-cuda8.0-cudnn7", and I export $anaconda_path/include and $anaconda_path/lib to CPLUS_INCLUDE_PATH and LD_LIBRARY_PATH  @alexge233

**Comment by wlgcqh** [comment]
libcaffe2.so and libcaffe2_gpu.so exists in /home/beiqi.qh/workplace/opt/anaconda2/lib. @alexge233

**Comment by alexge233** [comment]
And what does the linker actually see?
Try `echo $LD_LIBRARY_PATH` and `sudo ldconfig -p | grep 'libcaffe2*'`

**Comment by wlgcqh** [comment]
$echo $LD_LIBRARY_PATH
/home/beiqi.qh/workplace/opt/anaconda2/lib:/home/beiqi.qh/workplace/opt/lib:/home/beiqi.qh/workplace/cuda-8.0/lib64:

**Comment by alexge233** [comment]
You still haven't told us if your library is `ld` loaded.

**Comment by wlgcqh** [comment]
> You still haven't told us if your library is `ld` loaded.

I don't understand what you mean, cause I'm not sudo user, I can't execute "sudo ldconfig -p | grep libcaffe*"

**Comment by alexge233** [comment]
In that case it means you're not pointing the linker to the right directory. You say it is `/home/beiqi.qh/workplace/opt/anaconda2/lib` and you point LDFLAGS there, so I suggest you try changing the order of the llibraries. I know it's weird but it is actually a problem with LDFLAGS.
Try with `libcaffe` in a different order because the linker is telling us those symbols don't exist.
Also, try to verify this library has those methods:

```
nm -D /home/beiqi.qh/workplace/opt/anaconda2/lib/libcaffe2.so | grep "gTypeNames"
nm -D /home/beiqi.qh/workplace/opt/anaconda2/lib/libcaffe2.so | grep "EnforceNotMet"
```
The `gTypeNames` does not seem to be part of `caffe2` so I am guessing you need to rearrange the order of `protobuf` and `glog` amongst others. Chances are you need first `caffe` then the libraries it depends on.

**Comment by wlgcqh** [comment]
I try so many times as you said, but failed. could you teach me how to write correct Makefile. @alexge233

**Comment by wlgcqh** [comment]
/tmp/ccyoghYP.o: In function `caffe2::run()':
/home/beiqi.qh/workplace/test/test.cpp:25: undefined reference to `caffe2::Workspace::CreateBlob(std::string const&)'
/home/beiqi.qh/workplace/test/test.cpp:26: undefined reference to `caffe2::Workspace::GetBlob(std::string const&)'
