### ISSUE TITLE
Make issue

### ISSUE THREAD

**Issue by Alchemist77** [leonardvandriel/caffe2_cpp_tutorial#8]
Hello,

I have an issue during making the folder. I cannot found some function in operator folder.
Can you suggest me how to set up library path or something?
(I already installed caffe2 with cuda 8.0 and it is working well)

jaeseok@jaeseok-To-be-filled-by-O-E-M:~/workspace/caffe2_cpp_tutorial-master$ make
make[1]: Entering directory '/home/jaeseok/workspace/caffe2_cpp_tutorial-master/build'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jaeseok/workspace/caffe2_cpp_tutorial-master/build
make[2]: Entering directory '/home/jaeseok/workspace/caffe2_cpp_tutorial-master/build'
make[3]: Entering directory '/home/jaeseok/workspace/caffe2_cpp_tutorial-master/build'
make[3]: Leaving directory '/home/jaeseok/workspace/caffe2_cpp_tutorial-master/build'
[ 61%] Built target caffe2_cpp
make[3]: Entering directory '/home/jaeseok/workspace/caffe2_cpp_tutorial-master/build'
make[3]: Leaving directory '/home/jaeseok/workspace/caffe2_cpp_tutorial-master/build'
[ 88%] Built target caffe2_cpp_gpu
make[3]: Entering directory '/home/jaeseok/workspace/caffe2_cpp_tutorial-master/build'
make[3]: Leaving directory '/home/jaeseok/workspace/caffe2_cpp_tutorial-master/build'
make[3]: Entering directory '/home/jaeseok/workspace/caffe2_cpp_tutorial-master/build'
[ 94%] Linking CXX executable ../bin/intro
**## **libcaffe2_cpp_gpu.a(caffe2_cpp_gpu_generated_mean_stdev_op.cu.o): In function `caffe2::(anonymous namespace)::CAFFE_ANONYMOUS_VARIABLE_CUDAMeanStdev()':
/home/jaeseok/workspace/caffe2_cpp_tutorial-master/src/caffe2/operator/mean_stdev_op.cu:44: undefined reference to `caffe2::(anonymous namespace)::CAFFE2_PLEASE_ADD_OPERATOR_SCHEMA_FOR_MeanStdev()'
libcaffe2_cpp_gpu.a(caffe2_cpp_gpu_generated_affine_scale_op.cu.o): In function `caffe2::(anonymous namespace)::CAFFE_ANONYMOUS_VARIABLE_CUDAAffineScale()':
/home/jaeseok/workspace/caffe2_cpp_tutorial-master/src/caffe2/operator/affine_scale_op.cu:85: undefined reference to `caffe2::(anonymous namespace)::CAFFE2_PLEASE_ADD_OPERATOR_SCHEMA_FOR_AffineScale()'
libcaffe2_cpp_gpu.a(caffe2_cpp_gpu_generated_affine_scale_op.cu.o): In function `caffe2::(anonymous namespace)::CAFFE_ANONYMOUS_VARIABLE_CUDAAffineScaleGradient()':
/home/jaeseok/workspace/caffe2_cpp_tutorial-master/src/caffe2/operator/affine_scale_op.cu:86: undefined reference to `caffe2::(anonymous namespace)::CAFFE2_PLEASE_ADD_OPERATOR_SCHEMA_FOR_AffineScaleGradient()'
libcaffe2_cpp_gpu.a(caffe2_cpp_gpu_generated_diagonal_op.cu.o): In function `caffe2::(anonymous namespace)::CAFFE_ANONYMOUS_VARIABLE_CUDADiagonal()':
/home/jaeseok/workspace/caffe2_cpp_tutorial-master/src/caffe2/operator/diagonal_op.cu:85: undefined reference to `caffe2::(anonymous namespace)::CAFFE2_PLEASE_ADD_OPERATOR_SCHEMA_FOR_Diagonal()'
libcaffe2_cpp_gpu.a(caffe2_cpp_gpu_generated_diagonal_op.cu.o): In function `caffe2::(anonymous namespace)::CAFFE_ANONYMOUS_VARIABLE_CUDADiagonalGradient()':
/home/jaeseok/workspace/caffe2_cpp_tutorial-master/src/caffe2/operator/diagonal_op.cu:86: undefined reference to `caffe2::(anonymous namespace)::CAFFE2_PLEASE_ADD_OPERATOR_SCHEMA_FOR_DiagonalGradient()'
libcaffe2_cpp_gpu.a(caffe2_cpp_gpu_generated_back_mean_op.cu.o): In function `caffe2::(anonymous namespace)::CAFFE_ANONYMOUS_VARIABLE_CUDABackMean()':
/home/jaeseok/workspace/caffe2_cpp_tutorial-master/src/caffe2/operator/back_mean_op.cu:72: undefined reference to `caffe2::(anonymous namespace)::CAFFE2_PLEASE_ADD_OPERATOR_SCHEMA_FOR_BackMean()'
libcaffe2_cpp_gpu.a(caffe2_cpp_gpu_generated_back_mean_op.cu.o): In function `caffe2::(anonymous namespace)::CAFFE_ANONYMOUS_VARIABLE_CUDABackMeanGradient()':
/home/jaeseok/workspace/caffe2_cpp_tutorial-master/src/caffe2/operator/back_mean_op.cu:73: undefined reference to `caffe2::(anonymous namespace)::CAFFE2_PLEASE_ADD_OPERATOR_SCHEMA_FOR_BackMeanGradient()'
collect2: error: ld returned 1 exit status
CMakeFiles/intro.dir/build.make:148: recipe for target '../bin/intro' failed
make[3]: *** [../bin/intro] Error 1
make[3]: Leaving directory '/home/jaeseok/workspace/caffe2_cpp_tutorial-master/build'
CMakeFiles/Makefile2:142: recipe for target 'CMakeFiles/intro.dir/all' failed
make[2]: *** [CMakeFiles/intro.dir/all] Error 2
make[2]: Leaving directory '/home/jaeseok/workspace/caffe2_cpp_tutorial-master/build'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/jaeseok/workspace/caffe2_cpp_tutorial-master/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2****

**Comment by leonardvandriel** [comment]
Hi @Alchemist77, 

Thanks for reporting the issue. Unfortunately I haven't been able to reproduce this error. The particular linker error `PLEASE_ADD_OPERATOR_SCHEMA_FOR_` was introduced in caffe2 recently (commit e16871d87). It seems to be related to namespaces.

Can you see which particular commit of the Caffe2 repo you used to build Caffe2?

**Comment by Alchemist77** [comment]
Hi  @leonardvandriel 

caffe2 repo is
/home/jaeseok/workspace/caffe2

caffe2_cpp_tutorial-master repo is
/home/jaeseok/workspace/caffe2_cpp_tutorial-master

In the folder named as caffe2_cpp_tutorial-master has caffe2 folder in src folder.
Also, when I installed caffe2(official), i also do make install command(to copy /usr/local)

Can you suggest me how to move the official caffe2 into your folder?
Thanks.

**Comment by leonardvandriel** [comment]
your setup should work find. Perhaps it's good to `git pull` on the Caffe2 repo and build again with `make clean`, `make`, etc.

I applied similar changes to the use of namespace in operators (commit 40a15e6900). Can you pull and see if this resolves the issue?
