### ISSUE TITLE
make error: identifier "TIndex" is undefine 

### ISSUE THREAD

**Issue by lqql2012** [leonardvandriel/caffe2_cpp_tutorial#89]
i had download and compile pytorch according to README,but still have problem:

/home/lqql/Digital_HumanPose/z_test/caffe2_cpp_tutorial/src/caffe2/operator/squared_l2_op.cu(28): error: identifier "TIndex" is undefined
1 error detected in the compilation of "/tmp/tmpxft_00003219_00000000-6_squared_l2_op.cpp1.ii".
CMake Error at caffe2_cpp_gpu_generated_squared_l2_op.cu.o.cmake:279 (message):
  Error generating file
  /home/lqql/Digital_HumanPose/z_test/caffe2_cpp_tutorial/build/CMakeFiles/caffe2_cpp_gpu.dir/src/caffe2/operator/./caffe2_cpp_gpu_generated_squared_l2_op.cu.o

CMakeFiles/caffe2_cpp_gpu.dir/build.make:98: recipe for target 'CMakeFiles/caffe2_cpp_gpu.dir/src/caffe2/operator/caffe2_cpp_gpu_generated_squared_l2_op.cu.o' failed
make[3]: *** [CMakeFiles/caffe2_cpp_gpu.dir/src/caffe2/operator/caffe2_cpp_gpu_generated_squared_l2_op.cu.o] Error 1
make[3]: Leaving directory '/home/lqql/Digital_HumanPose/z_test/caffe2_cpp_tutorial/build'
CMakeFiles/Makefile2:375: recipe for target 'CMakeFiles/caffe2_cpp_gpu.dir/all' failed
make[2]: *** [CMakeFiles/caffe2_cpp_gpu.dir/all] Error 2
make[2]: Leaving directory '/home/lqql/Digital_HumanPose/z_test/caffe2_cpp_tutorial/build'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/lqql/Digital_HumanPose/z_test/caffe2_cpp_tutorial/build'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by helloahn** [comment]
I got the same one.

**Comment by alexge233** [comment]
you're mixing versions and Caffe2 is [currently undergoing changes](https://github.com/leonardvandriel/caffe2_cpp_tutorial/issues/83#issuecomment-475727022)!
