### ISSUE TITLE
Issue building project as CMake external project

### ISSUE THREAD

**Issue by charlesrwest** [leonardvandriel/caffe2_cpp_tutorial#9]
Hello again,

I've looked through the changes/helper functions you've made since the initial project and really like them (more than mine).  I am going to try to use them in my own project by linking to your repo via cmake.  However, I am running into some issues.

Project (if you wish to reproduce)
https://github.com/charlesrwest/CRWMachineLearning

I'm including your project by the following:
```
include(ExternalProject)

ExternalProject_Add(
  caffe2_cpp_tutorial

  GIT_REPOSITORY "https://github.com/leonardvandriel/caffe2_cpp_tutorial.git"
  GIT_TAG "master"
  
  UPDATE_COMMAND ""
  PATCH_COMMAND ""
  
  SOURCE_DIR "${CMAKE_SOURCE_DIR}/3rdparty/caffe2_cpp_tutorial"
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${GLOBAL_OUTPUT_PATH}/caffe2_cpp_tutorial
 
  TEST_COMMAND ""
)
```
Building from /build inside of your project works on my machine.  However, building as a sub-project only manages to build the libraries and then crashes (linker error) when it tries to build the binaries (I've yet to determine a way to get it only to build the libraries as an external project).

> charlesrwest@Telos:~/cpp/projects/caffe2/cpp/CRWMachineLearning/build$ cmake ../
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/charlesrwest/cpp/projects/caffe2/cpp/CRWMachineLearning/build
> charlesrwest@Telos:~/cpp/projects/caffe2/cpp/CRWMachineLearning/build$ make
> Scanning dependencies of target caffe2_cpp_tutorial
> [  7%] Creating directories for 'caffe2_cpp_tutorial'
> [ 15%] Performing download step (git clone) for 'caffe2_cpp_tutorial'
> Cloning into 'caffe2_cpp_tutorial'...
> Already on 'master'
> Your branch is up-to-date with 'origin/master'.
> [ 23%] No patch step for 'caffe2_cpp_tutorial'
> [ 30%] No update step for 'caffe2_cpp_tutorial'
> [ 38%] Performing configure step for 'caffe2_cpp_tutorial'
> -- The C compiler identification is GNU 5.4.0
> -- The CXX compiler identification is GNU 5.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Looking for pthread_create
> -- Looking for pthread_create - not found
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE  
> -- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/charlesrwest/cpp/projects/caffe2/cpp/CRWMachineLearning/build/caffe2_cpp_tutorial-prefix/src/caffe2_cpp_tutorial-build
> [ 46%] Performing build step for 'caffe2_cpp_tutorial'
> Scanning dependencies of target caffe2_cpp
> [  2%] Building CXX object CMakeFiles/caffe2_cpp.dir/src/caffe2/util/tensor.cc.o
> [  5%] Building CXX object CMakeFiles/caffe2_cpp.dir/src/caffe2/util/model.cc.o
> [  7%] Building CXX object CMakeFiles/caffe2_cpp.dir/src/caffe2/util/net.cc.o
> [ 10%] Building CXX object CMakeFiles/caffe2_cpp.dir/src/caffe2/util/blob.cc.o
> [ 12%] Building CXX object CMakeFiles/caffe2_cpp.dir/src/caffe2/operator/affine_scale_op.cc.o
> [ 15%] Building CXX object CMakeFiles/caffe2_cpp.dir/src/caffe2/operator/mean_stdev_op.cc.o
> [ 17%] Building CXX object CMakeFiles/caffe2_cpp.dir/src/caffe2/operator/back_mean_op.cc.o
> [ 20%] Building CXX object CMakeFiles/caffe2_cpp.dir/src/caffe2/operator/diagonal_op.cc.o
> [ 23%] Building CXX object CMakeFiles/caffe2_cpp.dir/src/caffe2/operator/show_worst_op.cc.o
> [ 25%] Building CXX object CMakeFiles/caffe2_cpp.dir/src/caffe2/operator/cout_op.cc.o
> [ 28%] Building CXX object CMakeFiles/caffe2_cpp.dir/src/caffe2/operator/zero_one_op.cc.o
> [ 30%] Linking CXX static library libcaffe2_cpp.a
> [ 30%] Built target caffe2_cpp
> [ 33%] Building NVCC (Device) object CMakeFiles/caffe2_cpp_gpu.dir/src/caffe2/operator/caffe2_cpp_gpu_generated_mean_stdev_op.cu.o
> [ 35%] Building NVCC (Device) object CMakeFiles/caffe2_cpp_gpu.dir/src/caffe2/operator/caffe2_cpp_gpu_generated_back_mean_op.cu.o
> [ 38%] Building NVCC (Device) object CMakeFiles/caffe2_cpp_gpu.dir/src/caffe2/operator/caffe2_cpp_gpu_generated_diagonal_op.cu.o
> [ 41%] Building NVCC (Device) object CMakeFiles/caffe2_cpp_gpu.dir/src/caffe2/operator/caffe2_cpp_gpu_generated_affine_scale_op.cu.o
> Scanning dependencies of target caffe2_cpp_gpu
> [ 43%] Linking CXX static library libcaffe2_cpp_gpu.a
> [ 43%] Built target caffe2_cpp_gpu
> Scanning dependencies of target intro
> [ 46%] Building CXX object CMakeFiles/intro.dir/src/caffe2/binaries/intro.cc.o
> [ 48%] Linking CXX executable /home/charlesrwest/cpp/projects/caffe2/cpp/CRWMachineLearning/3rdparty/caffe2_cpp_tutorial/bin/intro
> /usr/bin/ld: libcaffe2_cpp.a(blob.cc.o): undefined reference to symbol 'curandDestroyGenerator'
> /usr/local/cuda-8.0/lib64/libcurand.so.8.0: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status
> CMakeFiles/intro.dir/build.make:122: recipe for target '/home/charlesrwest/cpp/projects/caffe2/cpp/CRWMachineLearning/3rdparty/caffe2_cpp_tutorial/bin/intro' failed
> make[5]: *** [/home/charlesrwest/cpp/projects/caffe2/cpp/CRWMachineLearning/3rdparty/caffe2_cpp_tutorial/bin/intro] Error 1
> CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/intro.dir/all' failed
> make[4]: *** [CMakeFiles/intro.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make[3]: *** [all] Error 2
> CMakeFiles/caffe2_cpp_tutorial.dir/build.make:112: recipe for target 'caffe2_cpp_tutorial-prefix/src/caffe2_cpp_tutorial-stamp/caffe2_cpp_tutorial-build' failed
> make[2]: *** [caffe2_cpp_tutorial-prefix/src/caffe2_cpp_tutorial-stamp/caffe2_cpp_tutorial-build] Error 2
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/caffe2_cpp_tutorial.dir/all' failed
> make[1]: *** [CMakeFiles/caffe2_cpp_tutorial.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by charlesrwest** [comment]
Further investigation revealed that the reason for the different build results was that my stand aloe copy of this project was out of date.  I've started going through the commits and I haven't yet found the exact change but commit 5c2fbf9cc12a87b24300a6bd2cf7f309cf9511d8 compiles for me.

**Comment by charlesrwest** [comment]
> 5af3768086e81321c9609a15a0d0167e53bfe2c9
is the last working commit for me, meaning that the 
> d7e5b543d05d4fccfd63de1a00caf056a131ea73
commit broke building on my system (presumably from removing the nccl reference).  Digging into details.

**Comment by charlesrwest** [comment]
Both d7e5b54 and HEAD fail with the same error (Ubuntu 16.04 64 bit, if that helps). 
/usr/bin/ld: libcaffe2_cpp.a(blob.cc.o): undefined reference to symbol 'curandDestroyGenerator'
/usr/local/cuda-8.0/lib64/libcurand.so.8.0: error adding symbols: DSO missing from command line

**Comment by charlesrwest** [comment]
If I change the cmake variable from CUDA_CURAND_LIBRARY to CUDA_curand_LIBRARY, it makes it further to:
/usr/local/lib/libCaffe2_GPU.so: undefined reference to `ncclReduceScatter'

**Comment by charlesrwest** [comment]
Perhaps some of the difference is related to the cmake version (greping through files):
usr/share/cmake-3.5/Modules/FindCUDA.cmake:#   CUDA_curand_LIBRARY   -- CUDA Random Number Generation library.
usr/share/cmake-3.5/Modules/FindCUDA.cmake:  unset(CUDA_curand_LIBRARY CACHE)

**Comment by alexge233** [comment]
My guess is that you have built libCaffe2_GPU **with** nccl shared linkage, and your internal code is somehow referencing a call to nccl which is not being used to link your application/library.
What is the output of `readelf -d libCaffe2_GPU.so` and similarly what do you link to?

**Comment by leonardvandriel** [comment]
I reversed some of the recent linker changes in commit 37d38bd. Can you pull and see if that resolves the issue?
